--Min/Max Value
MIN_ID		=1000		--4 digit, by DataManager::GetDesc()
MAX_ID		=268435455	--9 digit, by DataManager::GetDesc()
MAX_COUNTER	=65535		--max number for adding/removing counters, by card::add_counter(), field::remove_counter()
MAX_NUMBER	=999999999	--Max number allowed in YGOPro
--Card ID
CARD_COUNTER_HOLDER	=10000001	--Counter holder (Unofficial card)
CARD_COPPER			=10001001	--Copper
CARD_CURSE			=10001002	--Curse
CARD_ESTATE			=10001003	--Estate
CARD_SILVER			=10001004	--Silver
CARD_DUCHY			=10001005	--Duchy
CARD_GOLD			=10001006	--Gold
CARD_PROVINCE		=10001007	--Province
CARD_VASSAL			=10001035	--EVENT_CUSTOM+EVENT_PLAY_ACTION
--Location
LOCATION_ALL		=0xff		--All locations
LOCATION_DECK		=0x01		--Deck
LOCATION_HAND		=0x02		--Hand
LOCATION_MZONE		=0x04		--Top Kingdom cards (sequences 0~4)
LOCATION_SZONE		=0x08		--Bottom Kingdom cards (sequences 0~4)
LOCATION_DPILE		=0x10		--Discard pile
LOCATION_INPLAY		=0x20		--In play (requires Auxiliary.InPlayFilter)
LOCATION_TRASH		=0x20		--Trash (requires Auxiliary.TrashFilter)
LOCATION_EXTRA		=0x40		--(unused)
LOCATION_OVERLAY	=0x80		--(unused)
LOCATION_SUPPLY		=0x0c		--Supply (LOCATION_MZONE+LOCATION_SZONE)
--Location (for redirect)
--If you specify LOCATION_DECK in the redirection effect, the card will return to the top of the Deck
LOCATION_DECKBOT	=0x10001	--(unused)
LOCATION_DECKSHF	=0x20001	--(unused)
--Deck Sequence (for Duel.SendtoDeck)
SEQ_DECK_TOP		=0		--Return to the top of the Deck
SEQ_DECK_BOTTOM		=1		--Return to the bottom of the Deck
SEQ_DECK_SHUFFLE	=2		--Shuffle into the Deck
SEQ_DECK_UNEXIST	=-2		--Disappear from the game
--Zone Sequence (for Card.GetSequence, Card.GetPreviousSequence, etc.)
SEQ_COPPER			=0		--Top leftmost Supply Zone
SEQ_SILVER			=1		--Top center-left Supply Zone
SEQ_GOLD			=2		--Top center Supply Zone
SEQ_ESTATE			=0		--Bottom leftmost Supply Zone
SEQ_DUCHY			=1		--Bottom center-left Supply Zone
SEQ_PROVINCE		=2		--Bottom center Supply Zone
SEQ_CURSE			=3		--Bottom leftmost Supply Zone
--Zone (Location + Sequence, can be used for EFFECT_DISABLE_FIELD)
--Base card Zones
ZONE_COPPER			=0x1	--Copper
ZONE_SILVER			=0x2	--Silver
ZONE_GOLD			=0x4	--Gold
ZONE_ESTATE			=0x1	--Estate
ZONE_DUCHY			=0x2	--Duchy
ZONE_PROVINCE		=0x4	--Province
ZONE_CURSE			=0x8	--Curse
--Position
POS_FACEUP_ATTACK		=0x1	--Face-up Attack Position
POS_FACEDOWN_ATTACK		=0x2	--Face-down Attack Position
POS_FACEUP_DEFENSE		=0x4	--Face-up Defense Position
POS_FACEDOWN_DEFENSE	=0x8	--Face-down Defense Position
POS_FACEUP				=0x5	--Face-up Position
POS_FACEDOWN			=0xa	--Face-down Position
POS_ATTACK				=0x3	--Attack Position
POS_DEFENSE				=0xc	--Defense Position
--Card Type
TYPE_ALL			=0x4ffffff	--All Card Types
TYPE_MONSTER		=0x1		--(unused)
TYPE_ACTION			=0x2		--Action
TYPE_TREASURE		=0x4		--Treasure
TYPE_TOKEN			=0x10		--(reserved) Token
TYPE_VICTORY		=0x20		--Victory
TYPE_FUSION			=0x40		--(unused)
TYPE_CURSE			=0x80		--Curse
TYPE_ATTACK			=0x100		--Attack
TYPE_REACTION		=0x200		--Reaction
TYPE_UNION			=0x400		--(unused)
TYPE_DUAL			=0x800		--(unused)
TYPE_TUNER			=0x1000		--(unused)
TYPE_SYNCHRO		=0x2000		--(unused)
TYPE_TOKEN			=0x4000		--(unused)
TYPE_QUICKPLAY		=0x10000	--(unused)
TYPE_CONTINUOUS		=0x20000	--(unused)
TYPE_EQUIP			=0x40000	--(unused)
TYPE_FIELD			=0x80000	--(unused)
TYPE_COUNTER		=0x100000	--(unused)
TYPE_FLIP			=0x200000	--(unused)
TYPE_TOON			=0x400000	--(unused)
TYPE_XYZ			=0x800000	--(unused)
TYPE_PENDULUM		=0x1000000	--(unused)
TYPE_SPSUMMON		=0x2000000	--(unused)
TYPE_LINK			=0x4000000	--(unused)
--Attribute
ATTRIBUTE_ALL		=0xff		--All Attributes
ATTRIBUTE_EARTH		=0x01		--(unused)
ATTRIBUTE_WATER		=0x02		--(unused)
ATTRIBUTE_FIRE		=0x04		--(unused)
ATTRIBUTE_WIND		=0x08		--(unused)
ATTRIBUTE_LIGHT		=0x10		--(unused)
ATTRIBUTE_DARK		=0x20		--(unused)
ATTRIBUTE_DIVINE	=0x40		--(unused)
--Race (Type)
RACE_ALL			=0x1ffffff	--All Types
RACE_WARRIOR		=0x1		--(unused)
RACE_SPELLCASTER	=0x2		--(unused)
RACE_FAIRY			=0x4		--(unused)
RACE_FIEND			=0x8		--(unused)
RACE_ZOMBIE			=0x10		--(unused)
RACE_MACHINE		=0x20		--(unused)
RACE_AQUA			=0x40		--(unused)
RACE_PYRO			=0x80		--(unused)
RACE_ROCK			=0x100		--(unused)
RACE_WINDBEAST		=0x200		--(unused)
RACE_PLANT			=0x400		--(unused)
RACE_INSECT			=0x800		--(unused)
RACE_THUNDER		=0x1000		--(unused)
RACE_DRAGON			=0x2000		--(unused)
RACE_BEAST			=0x4000		--(unused)
RACE_BEASTWARRIOR	=0x8000		--(unused)
RACE_DINOSAUR		=0x10000	--(unused)
RACE_FISH			=0x20000	--(unused)
RACE_SEASERPENT		=0x40000	--(unused)
RACE_REPTILE		=0x80000	--(unused)
RACE_PSYCHO			=0x100000	--(unused)
RACE_DIVINE			=0x200000	--(unused)
RACE_CREATORGOD		=0x400000	--(unused)
RACE_WYRM			=0x800000	--(unused)
RACE_CYBERSE		=0x1000000	--(unused)
--Reason
--The reason for sending a card to another location
REASON_DESTROY		=0x1		--(unused)
REASON_RELEASE		=0x2		--(unused)
REASON_TEMPORARY	=0x4		--(unused)
REASON_MATERIAL		=0x8		--(unused)
REASON_SUMMON		=0x10		--(unused)
REASON_BATTLE		=0x20		--(unused)
REASON_EFFECT		=0x40		--Effect
REASON_COST			=0x80		--(unused) Cost
REASON_ADJUST		=0x100		--(unused)
REASON_LOST_TARGET	=0x200		--(unused)
REASON_RULE			=0x400		--Rule
REASON_SPSUMMON		=0x800		--(unused)
REASON_DISSUMMON	=0x1000		--(unused)
REASON_FLIP			=0x2000		--(unused)
REASON_DISCARD		=0x4000		--(unused)
REASON_RDAMAGE		=0x8000		--(unused)
REASON_RRECOVER		=0x10000	--(unused)
REASON_RETURN		=0x20000	--(unused)
REASON_FUSION		=0x40000	--(unused)
REASON_SYNCHRO		=0x80000	--(unused)
REASON_RITUAL		=0x100000	--(unused)
REASON_XYZ			=0x200000	--(unused)
REASON_REPLACE		=0x1000000	--(unused)
REASON_DRAW			=0x2000000	--(unused)
REASON_REDIRECT		=0x4000000	--(unused)
REASON_REVEAL		=0x8000000	--(unused)
REASON_LINK			=0x10000000	--(unused)
REASON_TRASH		=0x20000000	--Trashed a card
--Location Reason
LOCATION_REASON_TOFIELD		=0x1	--(unused)
LOCATION_REASON_CONTROL		=0x2	--(unused)
LOCATION_REASON_COUNT		=0x4	--(unused, only available in YGOPro Percy)
--Win Reason
WIN_REASON_VP				=0x1	--Had the most VP.
--Summon Type
SUMMON_TYPE_NORMAL		=0x10000000 --(unused)
SUMMON_TYPE_ADVANCE		=0x11000000 --(unused)
SUMMON_TYPE_DUAL		=0x12000000	--(unused)
SUMMON_TYPE_FLIP		=0x20000000	--(unused)
SUMMON_TYPE_SPECIAL		=0x40000000	--(unused)
SUMMON_TYPE_FUSION		=0x43000000	--(unused)
SUMMON_TYPE_RITUAL		=0x45000000	--(unused)
SUMMON_TYPE_SYNCHRO		=0x46000000	--(unused)
SUMMON_TYPE_XYZ			=0x49000000	--(unused)
SUMMON_TYPE_PENDULUM	=0x4a000000 --(unused)
SUMMON_TYPE_LINK		=0x4c000000	--(unused)
--Summon Value
SUMMON_VALUE_SELF					=0x1	--(unused)
SUMMON_VALUE_DARK_FUSION			=0x10	--(unused)
SUMMON_VALUE_BLACK_GARDEN			=0x11	--(unused)
SUMMON_VALUE_SYNCHRO_MATERIAL		=0x12	--(unused)
SUMMON_VALUE_DARK_SANCTUARY			=0x13	--(unused)
SUMMON_VALUE_MILLENNIUM_REVELATION	=0x14	--(unused)
SUMMON_VALUE_LV						=0x1000	--(unused)
SUMMON_VALUE_GLADIATOR				=0x2000	--(unused)
SUMMON_VALUE_EVOLTILE				=0x4000	--(unused)
--Card Status
STATUS_DISABLED				=0x0001		--(unused)
STATUS_TO_ENABLE			=0x0002		--(unused)
STATUS_TO_DISABLE			=0x0004		--(unused)
STATUS_PROC_COMPLETE		=0x0008		--(unused)
STATUS_SET_TURN				=0x0010		--(unused)
STATUS_NO_COST				=0x0020		--(reserved) No cost
STATUS_BATTLE_RESULT		=0x0040		--(unused)
STATUS_SPSUMMON_STEP		=0x0080		--(unused)
STATUS_FORM_CHANGED			=0x0100		--(unused)
STATUS_SUMMONING			=0x0200		--(unused)
STATUS_EFFECT_ENABLED		=0x0400		--(unused)
STATUS_KINGDOM				=0x0800		--Kingdom card
STATUS_DESTROY_CONFIRMED	=0x1000		--(unused)
STATUS_LEAVE_CONFIRMED		=0x2000		--(unused)
STATUS_BATTLE_DESTROYED		=0x4000		--(unused)
STATUS_COPYING_EFFECT		=0x8000		--(unused)
STATUS_CHAINING				=0x10000	--(unused)
STATUS_SUMMON_DISABLED		=0x20000	--(unused)
STATUS_ACTIVATE_DISABLED	=0x40000	--(unused)
STATUS_EFFECT_REPLACED		=0x80000	--(unused)
STATUS_FUTURE_FUSION		=0x100000	--(unused)
STATUS_ATTACK_CANCELED		=0x200000	--(unused)
STATUS_INITIALIZING			=0x400000	--(unused)
STATUS_ACTIVATED			=0x800000	--(unused, only available in YGOPro Percy)
STATUS_JUST_POS				=0x1000000	--(unused)
STATUS_CONTINUOUS_POS		=0x2000000	--(unused)
STATUS_FORBIDDEN			=0x4000000	--(unused)
STATUS_ACT_FROM_HAND		=0x8000000	--(unused)
STATUS_OPPO_BATTLE			=0x10000000	--(unused)
STATUS_FLIP_SUMMON_TURN		=0x20000000	--(unused)
STATUS_SPSUMMON_TURN		=0x40000000	--(unused)
--Assume
ASSUME_CODE			=1	--(unused)
ASSUME_TYPE			=2	--(unused)
ASSUME_LEVEL		=3	--(unused)
ASSUME_RANK			=4	--(unused)
ASSUME_ATTRIBUTE	=5	--(unused)
ASSUME_RACE			=6	--(unused)
ASSUME_ATTACK		=7	--(unused)
ASSUME_DEFENSE		=8	--(unused)
ASSUME_LINK			=9	--(unused, only available in YGOPro Percy)
ASSUME_LINKMARKER	=10	--(unused, only available in YGOPro Percy)
--Link Marker
LINK_MARKER_BOTTOM_LEFT		=0x001	--(unused)
LINK_MARKER_BOTTOM			=0x002	--(unused)
LINK_MARKER_BOTTOM_RIGHT	=0x004	--(unused)
LINK_MARKER_LEFT			=0x008	--(unused)
LINK_MARKER_RIGHT			=0x020	--(unused)
LINK_MARKER_TOP_LEFT		=0x040	--(unused)
LINK_MARKER_TOP				=0x080	--(unused)
LINK_MARKER_TOP_RIGHT		=0x100	--(unused)
--Counter
COUNTER_WITHOUT_PERMIT		=0x1000	--(unused)
COUNTER_NEED_ENABLE			=0x2000	--(unused)
--Note: The following do not exist as counters in the actual game
COUNTER_COPIES				=0x1001	--This represents how many cards exist in a pile
COUNTER_ACTIONS				=0x1002	--This represents the amount of Actions a player has
COUNTER_BUYS				=0x1003	--This represents the amount of Buys a player has
COUNTER_COINS				=0x1004	--This represents the amount of Coins a player has
--Phase
PHASE_ACTION		=0x01	--Action phase
PHASE_BUY			=0x02	--Buy phase
PHASE_CLEANUP		=0x04	--Clean-up phasee
PHASE_BATTLE_START	=0x08	--(unused) Start Step
PHASE_BATTLE_STEP	=0x10	--(unused) Battle Step
PHASE_DAMAGE		=0x20	--(unused) Damage Step
PHASE_DAMAGE_CAL	=0x40	--(unused) Damage calculation
PHASE_BATTLE		=0x80	--End Step
PHASE_MAIN2			=0x100	--Main Phase 2
PHASE_END			=0x200	--End Phase
--Player
PLAYER_ONE			=0		--Player who goes first
PLAYER_TWO			=1		--Player who goes second
PLAYER_NONE			=2		--No players
PLAYER_ALL			=3		--All players
PLAYER_OWNER		=nil	--player=PLAYER_OWNER in Duel.Sendto..(targets, player, reason)
PLAYER_SELF			=0		--player=PLAYER_SELF in Effect.SetCondition(Auxiliary.Function(player)), etc.
PLAYER_OPPO			=1		--player=PLAYER_OPPO in Effect.SetCondition(Auxiliary.Function(player)), etc.
--Chain Information
CHAININFO_CHAIN_COUNT			=0x01	--(unused)
CHAININFO_TRIGGERING_EFFECT		=0x02	--(unused)
CHAININFO_TRIGGERING_PLAYER		=0x04	--(unused)
CHAININFO_TRIGGERING_CONTROLER	=0x08	--(unused)
CHAININFO_TRIGGERING_LOCATION	=0x10	--(unused)
CHAININFO_TRIGGERING_SEQUENCE	=0x20	--(unused)
CHAININFO_TARGET_CARDS			=0x40	--(unused)
CHAININFO_TARGET_PLAYER			=0x80	--(unused)
CHAININFO_TARGET_PARAM			=0x100	--(unused)
CHAININFO_DISABLE_REASON		=0x200	--(unused)
CHAININFO_DISABLE_PLAYER		=0x400	--(unused)
CHAININFO_CHAIN_ID				=0x800	--(unused)
CHAININFO_TYPE					=0x1000	--(unused)
CHAININFO_EXTTYPE				=0x2000	--(unused)
CHAININFO_TRIGGERING_POSITION	=0x4000	--(unused)
--The following is not available in YGOPro Percy
CHAININFO_TRIGGERING_CODE		=0x8000		--(unused)
CHAININFO_TRIGGERING_CODE2		=0x10000	--(unused)
CHAININFO_TRIGGERING_LEVEL		=0x40000	--(unused)
CHAININFO_TRIGGERING_RANK		=0x80000	--(unused)
CHAININFO_TRIGGERING_ATTRIBUTE	=0x100000	--(unused)
CHAININFO_TRIGGERING_RACE		=0x200000	--(unused)
CHAININFO_TRIGGERING_ATTACK		=0x400000	--(unused)
CHAININFO_TRIGGERING_DEFENSE	=0x800000	--(unused)
--Reset
RESET_SELF_TURN		=0x10000000			--Reset on own turn (combined with RESET_PHASE)
RESET_OPPO_TURN		=0x20000000			--Reset on opponent's turn (combined with RESET_PHASE)
RESET_PHASE			=0x40000000			--Reset in a specific phase (combined with PHASE constant)
RESET_CHAIN			=0x80000000			--Reset when a Chain resolves
RESET_EVENT			=0x1000				--Reset under a specified condition (combined with following events)
RESET_CARD			=0x2000				--(unused)
RESET_CODE			=0x4000				--(unused)
RESET_COPY			=0x8000				--Reset the copied effect
--The following is used in combination with RESET_EVENT in SetReset
RESET_DISABLE		=0x00010000			--Reset when effect is negated (only applicable to owner==effect handler)
RESET_TURN_SET		=0x00020000			--Reset when face-down on the field
RESET_TOGRAVE		=0x00040000			--(unused)
RESET_INPLAY		=0x00080000			--Reset when put in play
RESET_TEMP_REMOVE	=0x00100000			--(unused)
RESET_TOHAND		=0x00200000			--(unused)
RESET_TODECK		=0x00400000			--(unused)
RESET_LEAVE			=0x00800000			--(unused)
RESET_TOFIELD		=0x01000000			--(unused)
RESET_CONTROL		=0x02000000			--(unused)
RESET_OVERLAY		=0x04000000			--(unused)
RESET_MSCHANGE		=0x08000000			--(unused)
--Reset combinations
RESETS_STANDARD		=0x1fe0000			--RESET_TURN_SET+RESET_TOGRAVE+RESET_INPLAY+RESET_TEMP_REMOVE+RESET_TOHAND+RESET_TODECK+RESET_LEAVE+RESET_TOFIELD
RESETS_REDIRECT		=0xc7e0000			--RESETS_STANDARD+RESET_OVERLAY+RESET_MSCHANGE-RESET_LEAVE-RESET_TOFIELD (EFFECT_LEAVE_FIELD_REDIRECT)
--Effect Type
--Classification of effects
EFFECT_TYPE_SINGLE			=0x0001		--Effect applied to only a single card on the field
EFFECT_TYPE_FIELD			=0x0002		--Effect applied to all cards/players in a location
EFFECT_TYPE_EQUIP			=0x0004		--(unused)
EFFECT_TYPE_ACTIONS			=0x0008		--(unused)
EFFECT_TYPE_ACTIVATE		=0x0010		--(unused)
EFFECT_TYPE_FLIP			=0x0020		--(unused)
EFFECT_TYPE_IGNITION		=0x0040		--(unused)
EFFECT_TYPE_TRIGGER_O		=0x0080		--(unused)
EFFECT_TYPE_QUICK_O			=0x0100		--Optional Quick Effect
EFFECT_TYPE_TRIGGER_F		=0x0200		--Mandatory Trigger Effect
EFFECT_TYPE_QUICK_F			=0x0400		--(unused)
EFFECT_TYPE_CONTINUOUS		=0x0800		--Continuous Effect, non-Chaining effect
EFFECT_TYPE_XMATERIAL		=0x1000		--(unused)
EFFECT_TYPE_GRANT			=0x2000		--(unused)
EFFECT_TYPE_TARGET			=0x4000		--(unused, not available in YGOPro Percy)
--Flag
--Characteristics of effects
EFFECT_FLAG_INITIAL				=0x0001		--(unused)
EFFECT_FLAG_FUNC_VALUE			=0x0002		--(unused)
EFFECT_FLAG_COUNT_LIMIT			=0x0004		--(unused)
EFFECT_FLAG_FIELD_ONLY			=0x0008		--(unused)
EFFECT_FLAG_CARD_TARGET			=0x0010		--(unused)
EFFECT_FLAG_IGNORE_RANGE		=0x0020		--Affects cards in all locations
EFFECT_FLAG_ABSOLUTE_TARGET		=0x0040		--(unused)
EFFECT_FLAG_IGNORE_IMMUNE		=0x0080		--Ignores effect immunity
EFFECT_FLAG_SET_AVAILABLE		=0x0100		--Affects face-down cards on the field
EFFECT_FLAG_CANNOT_NEGATE		=0x0200		--(unused)
EFFECT_FLAG_CANNOT_DISABLE		=0x0400		--Cannot be negated
EFFECT_FLAG_PLAYER_TARGET		=0x0800		--Targets players
EFFECT_FLAG_BOTH_SIDE			=0x1000		--(unused)
EFFECT_FLAG_COPY_INHERIT		=0x2000		--(unused)
EFFECT_FLAG_DAMAGE_STEP			=0x4000		--Can be activated during the Damage Step (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DAMAGE_CAL			=0x8000		--Can be activated during damage calculation (not required for EFFECT_TYPE_SINGLE)
EFFECT_FLAG_DELAY				=0x10000	--Optional Trigger Effect cannot miss timing
EFFECT_FLAG_SINGLE_RANGE		=0x20000	--Sets the range of EFFECT_TYPE_SINGLE effects
EFFECT_FLAG_UNCOPYABLE			=0x40000	--Cannot be copied
EFFECT_FLAG_OATH				=0x80000	--(unused)
EFFECT_FLAG_SPSUM_PARAM			=0x100000	--(unused)
EFFECT_FLAG_REPEAT				=0x200000	--(unused)
EFFECT_FLAG_NO_TURN_RESET		=0x400000	--"Once while face-up on the field"
EFFECT_FLAG_EVENT_PLAYER		=0x800000	--(unused)
EFFECT_FLAG_OWNER_RELATE		=0x1000000	--(unused)
EFFECT_FLAG_PLAY_PARAM			=0x2000000	--Put in play when played
EFFECT_FLAG_CLIENT_HINT			=0x4000000	--Enables a tooltip of the effect (can only be used outside initial_effect)
EFFECT_FLAG_CHAIN_UNIQUE		=0x8000000	--(deprecated, only available in YGOPro Percy)
EFFECT_FLAG_LIMIT_ZONE			=0x10000000	--(unused, not available in YGOPro Percy)
EFFECT_FLAG_COF					=0x20000000 --(deprecated)
EFFECT_FLAG_CVAL_CHECK			=0x40000000	--(deprecated, only available in YGOPro Percy)
EFFECT_FLAG_IMMEDIATELY_APPLY	=0x80000000	--(unused)

EFFECT_FLAG2_NAGA				=0x0001		--(deprecated)
EFFECT_FLAG2_COF				=0x0002		--(unused)
EFFECT_FLAG2_MAJESTIC_MUST_COPY	=0x80000000	--(unused, only available in YGOPro Percy)
--Effect Code
EFFECT_IMMUNE_EFFECT				=1		--Unaffected by card effects
EFFECT_DISABLE						=2		--(unused)
EFFECT_CANNOT_DISABLE				=3		--(unused)
EFFECT_SET_CONTROL					=4		--(unused)
EFFECT_CANNOT_CHANGE_CONTROL		=5		--(unused)
EFFECT_CANNOT_ACTIVATE				=6		--(unused)
EFFECT_CANNOT_TRIGGER				=7		--(unused)
EFFECT_DISABLE_EFFECT				=8		--(unused)
EFFECT_DISABLE_CHAIN				=9		--(unused)
EFFECT_DISABLE_TRAPMONSTER			=10		--(unused)
EFFECT_CANNOT_INACTIVATE			=12		--(unused)
EFFECT_CANNOT_DISEFFECT				=13		--(unused)
EFFECT_CANNOT_CHANGE_POSITION		=14		--Cannot change position
EFFECT_TRAP_ACT_IN_HAND				=15		--(unused)
EFFECT_TRAP_ACT_IN_SET_TURN			=16		--(unused)
EFFECT_REMAIN_FIELD					=17		--(unused)
EFFECT_MONSTER_SSET					=18		--(unused)
EFFECT_CANNOT_SUMMON				=20		--Cannot Normal Summon monsters
EFFECT_CANNOT_FLIP_SUMMON			=21		--(unused)
EFFECT_CANNOT_SPECIAL_SUMMON		=22		--(unused)
EFFECT_CANNOT_MSET					=23		--Cannot Set monsters
EFFECT_CANNOT_SSET					=24		--Cannot Set Spells/Traps
EFFECT_CANNOT_DRAW					=25		--Cannot draw cards
EFFECT_CANNOT_DISABLE_SUMMON		=26		--(unused)
EFFECT_CANNOT_DISABLE_SPSUMMON		=27		--(unused)
EFFECT_SET_SUMMON_COUNT_LIMIT		=28		--(unused)
EFFECT_EXTRA_SUMMON_COUNT			=29		--(unused)
EFFECT_SPSUMMON_CONDITION			=30		--(unused)
EFFECT_REVIVE_LIMIT					=31		--(unused)
EFFECT_SUMMON_PROC					=32		--(unused)
EFFECT_LIMIT_SUMMON_PROC			=33		--(unused)
EFFECT_SPSUMMON_PROC				=34		--(unused)
EFFECT_EXTRA_SET_COUNT				=35		--(unused)
EFFECT_SET_PROC						=36		--(unused)
EFFECT_LIMIT_SET_PROC				=37		--(unused)
EFFECT_DEVINE_LIGHT					=38		--(unused)
EFFECT_CANNOT_DISABLE_FLIP_SUMMON	=39		--(unused)
EFFECT_INDESTRUCTIBLE				=40		--(unused)
EFFECT_INDESTRUCTIBLE_EFFECT		=41		--(unused)
EFFECT_INDESTRUCTIBLE_BATTLE		=42		--(unused)
EFFECT_UNRELEASABLE_SUM				=43		--(unused)
EFFECT_UNRELEASABLE_NONSUM			=44		--(unused)
EFFECT_DESTROY_SUBSTITUTE			=45		--(unused)
EFFECT_CANNOT_RELEASE				=46		--(unused)
EFFECT_INDESTRUCTIBLE_COUNT			=47		--(unused)
EFFECT_UNRELEASABLE_EFFECT			=48		--(unused)
EFFECT_DESTROY_REPLACE				=50		--(unused)
EFFECT_RELEASE_REPLACE				=51		--(unused)
EFFECT_SEND_REPLACE					=52		--(unused)
EFFECT_CANNOT_DISCARD_HAND			=55		--(unused)
EFFECT_CANNOT_DISCARD_DECK			=56		--(unused)
EFFECT_CANNOT_USE_AS_COST			=57		--(unused)
EFFECT_CANNOT_PLACE_COUNTER			=58		--(unused)
EFFECT_CANNOT_TO_GRAVE_AS_COST		=59		--(unused)
EFFECT_LEAVE_FIELD_REDIRECT			=60		--(unused)
EFFECT_TO_HAND_REDIRECT				=61		--(unused)
EFFECT_TO_DECK_REDIRECT				=62		--(unused)
EFFECT_TO_GRAVE_REDIRECT			=63		--(unused)
EFFECT_REMOVE_REDIRECT				=64		--(unused)
EFFECT_CANNOT_TO_HAND				=65		--(unused)
EFFECT_CANNOT_TO_DECK				=66		--(unused)
EFFECT_CANNOT_REMOVE				=67		--(unused)
EFFECT_CANNOT_TO_GRAVE				=68		--(unused)
EFFECT_CANNOT_TURN_SET				=69		--(unused)
EFFECT_CANNOT_BE_BATTLE_TARGET		=70		--(unused)
EFFECT_CANNOT_BE_EFFECT_TARGET		=71		--(unused)
EFFECT_IGNORE_BATTLE_TARGET			=72		--(unused)
EFFECT_CANNOT_DIRECT_ATTACK			=73		--(unused)
EFFECT_DIRECT_ATTACK				=74		--(unused)
EFFECT_DUAL_STATUS					=75		--(unused)
EFFECT_EQUIP_LIMIT					=76		--(unused)
EFFECT_DUAL_SUMMONABLE				=77		--(unused)
EFFECT_REVERSE_DAMAGE				=80		--(unused)
EFFECT_REVERSE_RECOVER				=81		--(unused)
EFFECT_CHANGE_DAMAGE				=82		--(unused)
EFFECT_REFLECT_DAMAGE				=83		--(unused)
EFFECT_CANNOT_ATTACK				=85		--(unused)
EFFECT_CANNOT_ATTACK_ANNOUNCE		=86		--(unused)
EFFECT_CANNOT_CHANGE_POS_E			=87		--(unused)
EFFECT_ACTIVATE_COST				=90		--(unused)
EFFECT_SUMMON_COST					=91		--(unused)
EFFECT_SPSUMMON_COST				=92		--(unused)
EFFECT_FLIPSUMMON_COST				=93		--(unused)
EFFECT_MSET_COST					=94		--(unused)
EFFECT_SSET_COST					=95		--(unused)
EFFECT_ATTACK_COST					=96		--(unused)

EFFECT_UPDATE_ATTACK				=100	--(unused)
EFFECT_SET_ATTACK					=101	--(unused)
EFFECT_SET_ATTACK_FINAL				=102	--(unused)
EFFECT_SET_BASE_ATTACK				=103	--(unused)
EFFECT_UPDATE_DEFENSE				=104	--(unused)
EFFECT_SET_DEFENSE					=105	--(unused)
EFFECT_SET_DEFENSE_FINAL			=106	--(unused)
EFFECT_SET_BASE_DEFENSE				=107	--(unused)
EFFECT_REVERSE_UPDATE				=108	--(unused)
EFFECT_SWAP_AD						=109	--(unused)
EFFECT_SWAP_BASE_AD					=110	--(unused)
EFFECT_SWAP_ATTACK_FINAL			=111	--(N/A)
EFFECT_SWAP_DEFENSE_FINAL			=112	--(N/A)
EFFECT_ADD_CODE						=113	--(unused)
EFFECT_CHANGE_CODE					=114	--(unused)
EFFECT_ADD_TYPE						=115	--(unused)
EFFECT_REMOVE_TYPE					=116	--(unused)
EFFECT_CHANGE_TYPE					=117	--(unused)
EFFECT_ADD_RACE						=120	--(unused)
EFFECT_REMOVE_RACE					=121	--(unused)
EFFECT_CHANGE_RACE					=122	--(unused)
EFFECT_ADD_ATTRIBUTE				=125	--(unused)
EFFECT_REMOVE_ATTRIBUTE				=126	--(unused)
EFFECT_CHANGE_ATTRIBUTE				=127	--(unused)
EFFECT_UPDATE_COST					=130	--(reserved) Increase/decrease cost
EFFECT_CHANGE_COST					=131	--(reserved) Change cost
EFFECT_UPDATE_RANK					=132	--(unused)
EFFECT_CHANGE_RANK					=133	--(unused)
EFFECT_UPDATE_LSCALE				=134	--(unused)
EFFECT_CHANGE_LSCALE				=135	--(unused)
EFFECT_UPDATE_RSCALE				=136	--(unused)
EFFECT_CHANGE_RSCALE				=137	--(unused)
EFFECT_SET_POSITION					=140	--(unused)
EFFECT_SELF_DESTROY					=141	--(unused)
EFFECT_SELF_TOGRAVE					=142	--(unused)
EFFECT_DOUBLE_TRIBUTE				=150	--(unused)
EFFECT_DECREASE_TRIBUTE				=151	--(unused)
EFFECT_DECREASE_TRIBUTE_SET			=152	--(unused)
EFFECT_EXTRA_RELEASE				=153	--(unused)
EFFECT_TRIBUTE_LIMIT				=154	--(unused)
EFFECT_EXTRA_RELEASE_SUM			=155	--(unused)
EFFECT_TRIPLE_TRIBUTE				=156	--(N/A)
EFFECT_ADD_EXTRA_TRIBUTE			=157	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_RELEASE_NONSUM			=158	--(unused, not available in YGOPro Percy)
EFFECT_PUBLIC						=160	--Card stays revealed
EFFECT_COUNTER_PERMIT				=0x10000--(unused)
EFFECT_COUNTER_LIMIT				=0x20000--(unused)
EFFECT_RCOUNTER_REPLACE				=0x30000--(unused)
EFFECT_LPCOST_CHANGE				=170	--(unused)
EFFECT_LPCOST_REPLACE				=171	--(unused)
EFFECT_SKIP_DP						=180	--Skip Draw Phase
EFFECT_SKIP_SP						=181	--Skip Standby Phase
EFFECT_SKIP_M1						=182	--(unused) Skip Main Phase 1
EFFECT_SKIP_BP						=183	--(unused) Skip Battle Phase
EFFECT_SKIP_M2						=184	--(unused) Skip Main Phase 2
EFFECT_CANNOT_BP					=185	--Cannot conduct Battle Phase
EFFECT_CANNOT_M2					=186	--Cannot conduct Main Phase 2
EFFECT_CANNOT_EP					=187	--Cannot conduct End Phase
EFFECT_SKIP_TURN					=188	--(unused)
EFFECT_DEFENSE_ATTACK				=190	--(unused)
EFFECT_MUST_ATTACK					=191	--(unused)
EFFECT_FIRST_ATTACK					=192	--(unused)
EFFECT_ATTACK_ALL					=193	--(unused)
EFFECT_EXTRA_ATTACK					=194	--(unused)
EFFECT_MUST_BE_ATTACKED				=195	--(unused, only available in YGOPro Percy)
EFFECT_ONLY_BE_ATTACKED				=196	--(unused)
EFFECT_ATTACK_DISABLED				=197	--(unused)
EFFECT_NO_BATTLE_DAMAGE				=200	--(unused)
EFFECT_AVOID_BATTLE_DAMAGE			=201	--(unused)
EFFECT_REFLECT_BATTLE_DAMAGE		=202	--(unused)
EFFECT_PIERCE						=203	--(unused)
EFFECT_BATTLE_DESTROY_REDIRECT		=204	--(unused)
EFFECT_BATTLE_DAMAGE_TO_EFFECT		=205	--(unused)
EFFECT_BOTH_BATTLE_DAMAGE			=206	--(unused, not available in YGOPro Percy)
EFFECT_ALSO_BATTLE_DAMAGE			=207	--(unused, not available in YGOPro Percy)
EFFECT_CHANGE_BATTLE_DAMAGE			=208	--(unused, not available in YGOPro Percy)
EFFECT_TOSS_COIN_REPLACE			=220	--(unused)
EFFECT_TOSS_DICE_REPLACE			=221	--(unused)
EFFECT_FUSION_MATERIAL				=230	--(unused)
EFFECT_CHAIN_MATERIAL				=231	--(unused)
EFFECT_SYNCHRO_MATERIAL				=232	--(unused)
EFFECT_XYZ_MATERIAL					=233	--(unused)
EFFECT_FUSION_SUBSTITUTE			=234	--(unused)
EFFECT_CANNOT_BE_FUSION_MATERIAL	=235	--(unused)
EFFECT_CANNOT_BE_SYNCHRO_MATERIAL	=236	--(unused)
EFFECT_SYNCHRO_MATERIAL_CUSTOM		=237	--(unused)
EFFECT_CANNOT_BE_XYZ_MATERIAL		=238	--(unused)
EFFECT_CANNOT_BE_LINK_MATERIAL		=239	--(unused)
EFFECT_SYNCHRO_LEVEL				=240	--(unused)
EFFECT_RITUAL_LEVEL					=241	--(unused)
EFFECT_XYZ_LEVEL					=242	--(unused)
EFFECT_EXTRA_RITUAL_MATERIAL		=243	--(unused)
EFFECT_NONTUNER						=244	--(unused)
EFFECT_OVERLAY_REMOVE_REPLACE		=245	--(unused)
EFFECT_SCRAP_CHIMERA				=246	--(unused)
EFFECT_TUNE_MAGICIAN_X				=247	--(unused)
EFFECT_TUNE_MAGICIAN_F				=248	--(unused, not available in YGOPro Percy)
EFFECT_PRE_MONSTER					=250	--(unused)
EFFECT_MATERIAL_CHECK				=251	--(unused)
EFFECT_DISABLE_FIELD				=260	--(unused)
EFFECT_USE_EXTRA_MZONE				=261	--(unused)
EFFECT_USE_EXTRA_SZONE				=262	--(unused)
EFFECT_MAX_MZONE					=263	--(unused)
EFFECT_MAX_SZONE					=264	--(unused)
EFFECT_FORCE_MZONE					=265	--(unused, only available in YGOPro Percy)
EFFECT_BECOME_LINKED_ZONE			=266	--(unused, only available in YGOPro Percy)
EFFECT_HAND_LIMIT					=270	--Change the hand size limit
EFFECT_DRAW_COUNT					=271	--Change the number of normal draws
EFFECT_SPIRIT_DONOT_RETURN			=280	--(unused)
EFFECT_SPIRIT_MAYNOT_RETURN			=281	--(unused)
EFFECT_CHANGE_ENVIRONMENT			=290	--(unused)
EFFECT_NECRO_VALLEY					=291	--(unused)
EFFECT_FORBIDDEN					=292	--(unused)
EFFECT_NECRO_VALLEY_IM				=293	--(unused)
EFFECT_REVERSE_DECK					=294	--(unused)
EFFECT_REMOVE_BRAINWASHING			=295	--(unused)
EFFECT_BP_TWICE						=296	--(unused)
EFFECT_UNIQUE_CHECK					=297	--(unused)
EFFECT_MATCH_KILL					=300	--(unused)
EFFECT_SYNCHRO_CHECK				=310	--(unused)
EFFECT_QP_ACT_IN_NTPHAND			=311	--(unused)
EFFECT_MUST_BE_MATERIAL				=312	--(unused, only available in YGOPro Percy)
EFFECT_TO_GRAVE_REDIRECT_CB			=313	--(unused)
EFFECT_CHANGE_LEVEL_FINAL			=314	--(unused, only available in YGOPro Percy)
EFFECT_CHANGE_RANK_FINAL			=315	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_FMATERIAL			=316	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_XMATERIAL			=317	--(unused, only available in YGOPro Percy)
EFFECT_MUST_BE_LMATERIAL			=318	--(unused, only available in YGOPro Percy)
EFFECT_SPSUMMON_PROC_G				=320	--(unused)
EFFECT_SPSUMMON_COUNT_LIMIT			=330	--(unused)
EFFECT_LEFT_SPSUMMON_COUNT			=331	--(unused)
EFFECT_CANNOT_SELECT_BATTLE_TARGET	=332	--(unused)
EFFECT_CANNOT_SELECT_EFFECT_TARGET	=333	--(unused)
EFFECT_ADD_SETCODE					=334	--(unused)
EFFECT_NO_EFFECT_DAMAGE				=335	--(unused)
EFFECT_UNSUMMONABLE_CARD			=336	--(unused, only available in YGOPro Percy)
EFFECT_DISABLE_CHAIN_FIELD			=337	--(N/A)
EFFECT_DISCARD_COST_CHANGE			=338	--(unused)
EFFECT_HAND_SYNCHRO					=339	--(unused)
EFFECT_ADD_FUSION_CODE				=340	--(unused)
EFFECT_ADD_FUSION_SETCODE			=341	--(unused)
EFFECT_RISE_TO_FULL_HEIGHT			=342	--(unused, only available in YGOPro Percy)
EFFECT_ONLY_ATTACK_MONSTER			=343	--(unused)
EFFECT_MUST_ATTACK_MONSTER			=344	--(unused)
EFFECT_PATRICIAN_OF_DARKNESS		=345	--(unused)
EFFECT_EXTRA_ATTACK_MONSTER			=346	--(unused)
EFFECT_UNION_STATUS					=347	--(unused)
EFFECT_OLDUNION_STATUS				=348	--(unused)
EFFECT_ADD_FUSION_ATTRIBUTE			=349	--(unused, reserved)
EFFECT_REMOVE_FUSION_ATTRIBUTE		=350	--(unused, reserved)
EFFECT_CHANGE_FUSION_ATTRIBUTE		=351	--(unused)
EFFECT_EXTRA_FUSION_MATERIAL		=352	--(unused)
EFFECT_TUNER_MATERIAL_LIMIT			=353	--(unused)
EFFECT_ADD_LINK_CODE				=354	--(unused)
EFFECT_ADD_LINK_SETCODE				=355	--(unused, reserved)
EFFECT_ADD_LINK_ATTRIBUTE			=356	--(unused, not available in YGOPro Percy)
EFFECT_ADD_LINK_RACE				=357	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_MATERIAL				=358	--(unused, only available in YGOPro Percy)
EFFECT_QP_ACT_IN_SET_TURN			=359	--(unused, not available in YGOPro Percy)
EFFECT_EXTRA_PENDULUM_SUMMON		=360	--(unused, not available in YGOPro Percy)
EFFECT_MATERIAL_LIMIT				=361	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_ATTACK			=362	--(unused, not available in YGOPro Percy)
EFFECT_SET_BATTLE_DEFENSE			=363	--(unused, not available in YGOPro Percy)
--The following is only available in YGOPro Percy
EFFECT_CANNOT_LOSE_DECK				=400	--Cannot lose when unable to draw a card
EFFECT_CANNOT_LOSE_LP				=401	--(unused)
EFFECT_CANNOT_LOSE_EFFECT			=402	--(unused)
EFFECT_BP_FIRST_TURN				=403	--(unused)
EFFECT_UNSTOPPABLE_ATTACK			=404	--(unused)
EFFECT_ALLOW_NEGATIVE				=405	--(unused)
EFFECT_SELF_ATTACK					=406	--(unused)
EFFECT_BECOME_QUICK					=407	--(unused)
EFFECT_LEVEL_RANK					=408	--(unused)
EFFECT_RANK_LEVEL					=409	--(unused)
EFFECT_LEVEL_RANK_S					=410	--(unused)
EFFECT_RANK_LEVEL_S					=411	--(unused)
EFFECT_UPDATE_LINK					=420	--(unused)
EFFECT_CHANGE_LINK					=421	--(unused)
EFFECT_CHANGE_LINK_FINAL			=422	--(unused)
EFFECT_ADD_LINKMARKER				=423	--(unused)
EFFECT_REMOVE_LINKMARKER			=424	--(unused)
EFFECT_CHANGE_LINKMARKER			=425	--(unused)
--The following is only available in YGOPro DO
EFFECT_CHANGE_VP					=600	--Set the VP a card is worth ("Gardens" 1-020)
EFFECT_PLAY_ACTION_TWICE			=601	--Action card may be played twice ("Throne Room" 1-024)
--Event Code
--Events that can be used as a trigger for Trigger Effects
EVENT_STARTUP					=1000	--(unused)
EVENT_FLIP						=1001	--(unused)
EVENT_FREE_CHAIN				=1002	--Open window to activate Ignition and Trigger Effects
EVENT_DESTROY					=1010	--(unused)
EVENT_REMOVE					=1011	--(unused)
EVENT_TO_HAND					=1012	--(unused)
EVENT_TO_DECK					=1013	--(unused)
EVENT_TO_GRAVE					=1014	--(unused)
EVENT_LEAVE_FIELD				=1015	--(unused)
EVENT_CHANGE_POS				=1016	--(unused)
EVENT_RELEASE					=1017	--(unused)
EVENT_DISCARD					=1018	--(unused)
EVENT_LEAVE_FIELD_P				=1019	--(unused)
EVENT_CHAIN_SOLVING				=1020	--(unused)
EVENT_CHAIN_ACTIVATING			=1021	--(unused)
EVENT_CHAIN_SOLVED				=1022	--After a Chain resolves
EVENT_CHAIN_ACTIVATED			=1023	--(N/A)
EVENT_CHAIN_NEGATED				=1024	--(unused)
EVENT_CHAIN_DISABLED			=1025	--(unused)
EVENT_CHAIN_END					=1026	--(unused)
EVENT_CHAINING					=1027	--When a card/effect is activating in response to another card/effect
EVENT_BECOME_TARGET				=1028	--(unused)
EVENT_DESTROYED					=1029	--(unused)
EVENT_MOVE						=1030	--(unused, not available in YGOPro Percy)
EVENT_ADJUST					=1040	--After adjusting the adjust_all() card
EVENT_SUMMON_SUCCESS			=1100	--(unused)
EVENT_FLIP_SUMMON_SUCCESS		=1101	--(unused)
EVENT_SPSUMMON_SUCCESS			=1102	--(unused)
EVENT_SUMMON					=1103	--(unused)
EVENT_FLIP_SUMMON				=1104	--(unused)
EVENT_SPSUMMON					=1105	--(unused)
EVENT_MSET						=1106	--(unused)
EVENT_SSET						=1107	--(unused)
EVENT_BE_MATERIAL				=1108	--(unused)
EVENT_BE_PRE_MATERIAL			=1109	--(unused)
EVENT_DRAW						=1110	--(unused)
EVENT_DAMAGE					=1111	--(unused)
EVENT_RECOVER					=1112	--(unused)
EVENT_PREDRAW					=1113	--(unused)
EVENT_SUMMON_NEGATED			=1114	--(unused, not available in YGOPro Percy)
EVENT_FLIP_SUMMON_NEGATED		=1115	--(unused, not available in YGOPro Percy)
EVENT_SPSUMMON_NEGATED			=1116	--(unused, not available in YGOPro Percy)
EVENT_CONTROL_CHANGED			=1120	--(unused)
EVENT_EQUIP						=1121	--(unused)
EVENT_ATTACK_ANNOUNCE			=1130	--(unused)
EVENT_BE_BATTLE_TARGET			=1131	--(unused)
EVENT_BATTLE_START				=1132	--(unused)
EVENT_BATTLE_CONFIRM			=1133	--(unused)
EVENT_PRE_DAMAGE_CALCULATE		=1134	--(unused)
EVENT_DAMAGE_CALCULATING		=1135	--(N/A)
EVENT_PRE_BATTLE_DAMAGE			=1136	--(unused)
EVENT_BATTLE_END				=1137	--(N/A)
EVENT_BATTLED					=1138	--(unused)
EVENT_BATTLE_DESTROYING			=1139	--(unused)
EVENT_BATTLE_DESTROYED			=1140	--(unused)
EVENT_DAMAGE_STEP_END			=1141	--(unused)
EVENT_ATTACK_DISABLED			=1142	--(unused)
EVENT_BATTLE_DAMAGE				=1143	--(unused)
EVENT_TOSS_DICE					=1150	--(unused)
EVENT_TOSS_COIN					=1151	--(unused)
EVENT_TOSS_COIN_NEGATE			=1152	--(unused)
EVENT_TOSS_DICE_NEGATE			=1153	--(unused)
EVENT_LEVEL_UP					=1200	--(unused)
EVENT_PAY_LPCOST				=1201	--(unused)
EVENT_DETACH_MATERIAL			=1202	--(unused)
EVENT_RETURN_TO_GRAVE			=1203	--(unused)
EVENT_TURN_END					=1210	--At the end of the turn
EVENT_PHASE						=0x1000	--During a phase of a turn (combined with PHASE constant)
EVENT_PHASE_START				=0x2000	--At the start of a phase of a turn (combined with PHASE constant)
EVENT_ADD_COUNTER				=0x10000	--(unused, combined with counter ID)
EVENT_REMOVE_COUNTER			=0x20000	--(unused, combined with counter ID)
EVENT_CUSTOM					=0x10000000	--Custom event
--The following is only available in YGOPro DO
EVENT_PLAY_ACTION				=CARD_VASSAL	--Play an Action card
--Effect Category
--Hint
--Message displayed in the center of the screen
HINT_EVENT				=1	--Display event text
HINT_MESSAGE			=2	--Display a string
HINT_SELECTMSG			=3	--Display a selection message
HINT_OPSELECTED			=4	--Display the selected effect
HINT_EFFECT				=5	--(unused)
HINT_RACE				=6	--(unused)
HINT_ATTRIB				=7	--(unused)
HINT_CODE				=8	--(unused)
HINT_NUMBER				=9	--(unused)
HINT_CARD				=10	--Display the card name selected by the effect
HINT_ZONE				=11	--(unused, not available in YGOPro Percy)
--Card Hint
--Message displayed in the white frame that appears when you place the cursor on the card
CHINT_TURN				=1	--(unused)
CHINT_CARD				=2	--(unused)
CHINT_RACE				=3	--(unused)
CHINT_ATTRIBUTE			=4	--(unused)
CHINT_NUMBER			=5	--(unused)
CHINT_DESC				=6	--(unused)
--Opcode
OPCODE_ADD				=0x40000000		--(unused)
OPCODE_SUB				=0x40000001		--(unused)
OPCODE_MUL				=0x40000002		--(unused)
OPCODE_DIV				=0x40000003		--(unused)
OPCODE_AND				=0x40000004		--(unused)
OPCODE_OR				=0x40000005		--(unused)
OPCODE_NEG				=0x40000006		--(unused)
OPCODE_NOT				=0x40000007		--(unused)
OPCODE_ISCODE			=0x40000100		--(unused)
OPCODE_ISSETCARD		=0x40000101		--(unused)
OPCODE_ISTYPE			=0x40000102		--(unused)
OPCODE_ISRACE			=0x40000103		--(unused)
OPCODE_ISATTRIBUTE		=0x40000104		--(unused)
--Damage
DOUBLE_DAMAGE			=0x80000000		--(unused, not available in YGOPro Percy)
HALF_DAMAGE				=0x80000001		--(unused, not available in YGOPro Percy)
--Hint Message
--Message displayed at the top of the screen
HINTMSG_GAIN			=500	--Select a card to gain.
HINTMSG_DISCARD			=501	--Select a card to discard.
HINTMSG_PLAY			=502	--Select a card to play.
HINTMSG_TRASH			=503	--Select a card to trash.
HINTMSG_TODECK			=504	--Select a card to put onto the deck.
HINTMSG_PLAYTWICE		=505	--Select a card to play twice.
--Information displayed in a dialog box
ERROR_NOTARGETS			=1630	--There is no applicable card.
--Yes No Message (for Duel.SelectYesNo)
YESNOMSG_DECKTODPILE	=600	--Put your deck into the discard pile?
YESNOMSG_DISCARDDECK	=601	--Discard a card from the deck?
YESNOMSG_GAINCARD		=602	--Gain a card?
YESNOMSG_PLAY			=603	--Play a card?
--Option (for Duel.SelectOption)
OPTION_HEADS			=60		--(unused)
OPTION_TAILS			=61		--(unused)
--Description (for SetDescription, EFFECT_FLAG_CLIENT_HINT)
DESC_PLAY_TWICE			=300	--May be played twice
--Timing
--Free Chain activation timing
TIMING_ACTION_PHASE			=0x1		--Action phase
TIMING_BUY_PHASE			=0x2		--Buy phase
TIMING_MAIN_END				=0x4		--(unused)
TIMING_BATTLE_START			=0x8		--(unused)
TIMING_BATTLE_END			=0x10		--(unused)
TIMING_END_PHASE			=0x20		--(unused)
TIMING_SUMMON				=0x40		--(unused)
TIMING_SPSUMMON				=0x80		--(unused)
TIMING_FLIPSUMMON			=0x100		--(unused)
TIMING_MSET					=0x200		--(unused)
TIMING_SSET					=0x400		--(unused)
TIMING_POS_CHANGE			=0x800		--(unused)
TIMING_ATTACK				=0x1000		--(unused)
TIMING_DAMAGE_STEP			=0x2000		--(unused)
TIMING_DAMAGE_CAL			=0x4000		--(unused)
TIMING_CHAIN_END			=0x8000		--(unused)
TIMING_DRAW					=0x10000	--(unused)
TIMING_DAMAGE				=0x20000	--(unused)
TIMING_RECOVER				=0x40000	--(unused)
TIMING_DESTROY				=0x80000	--(unused)
TIMING_REMOVE				=0x100000	--(unused)
TIMING_TOHAND				=0x200000	--(unused)
TIMING_TODECK				=0x400000	--(unused)
TIMING_TOGRAVE				=0x800000	--(unused)
TIMING_BATTLE_PHASE			=0x1000000	--(unused)
TIMING_EQUIP				=0x2000000	--(unused)
TIMING_BATTLE_STEP_END		=0x4000000	--(unused)
--Timing combinations
TIMINGS_CHECK_MONSTER		=0x1c0		--(unused) TIMING_SUMMON+TIMING_SPSUMMON+TIMING_FLIPSUMMON
--Global Flag
--Special effect flag
GLOBALFLAG_DECK_REVERSE_CHECK	=0x1		--(unused)
GLOBALFLAG_BRAINWASHING_CHECK	=0x2		--(unused)
GLOBALFLAG_SCRAP_CHIMERA		=0x4		--(unused)
GLOBALFLAG_DELAYED_QUICKEFFECT	=0x8		--(N/A)
GLOBALFLAG_DETACH_EVENT			=0x10		--(unused)
GLOBALFLAG_MUST_BE_SMATERIAL	=0x20		--(unused)
GLOBALFLAG_SPSUMMON_COUNT		=0x40		--(unused)
GLOBALFLAG_XMAT_COUNT_LIMIT		=0x80		--(unused)
GLOBALFLAG_SELF_TOGRAVE			=0x100		--(unused)
GLOBALFLAG_SPSUMMON_ONCE		=0x200		--(unused)
GLOBALFLAG_TUNE_MAGICIAN		=0x400		--(unused)
--Effect Count Code
--Limit the number of effects that can be used
EFFECT_COUNT_CODE_OATH			=0x10000000	--(unused)
EFFECT_COUNT_CODE_DUEL			=0x20000000	--(unused)
EFFECT_COUNT_CODE_SINGLE		=0x1		--(unused)
--Duel Options
DUEL_TEST_MODE			=0x01	--Test mode (not currently available)
DUEL_ATTACK_FIRST_TURN	=0x02	--Can attack during the first turn (for puzzles)
DUEL_NO_CHAIN_HINT		=0x04	--(N/A)
DUEL_OBSOLETE_RULING	=0x08	--Use old rules
DUEL_PSEUDO_SHUFFLE		=0x10	--Do not shuffle Deck
DUEL_TAG_MODE			=0x20	--2v2
DUEL_SIMPLE_AI			=0x40	--Semi-automatic AI (for puzzles)
SPEED_DUEL				=0x80	--Speed Duel (only available in YGOPro Percy)
--Activity Counter
--global: 1-6 (binary: 5,6)
--custom: 1-5,7 (binary: 1-5)
ACTIVITY_SUMMON			=1		--(unused)
ACTIVITY_NORMALSUMMON	=2		--(unused)
ACTIVITY_SPSUMMON		=3		--(unused)
ACTIVITY_FLIPSUMMON		=4		--(unused)
ACTIVITY_ATTACK			=5		--(unused)
ACTIVITY_BATTLE_PHASE	=6		--(unused, not available in Duel.AddCustomActivityCounter)
ACTIVITY_CHAIN			=7		--(unused, only available in Duel.AddCustomActivityCounter)
--Announce Type
ANNOUNCE_CARD			=0x7	--(unused, only available in YGOPro Percy)
ANNOUNCE_CARD_FILTER	=0x8	--(unused, only available in YGOPro Percy)
